Add tests for check dashboard functionality
arsenhovh/TAF-Project pull request #1
Opened 2024-04-01 13:10 UTC by arsenhovh

2024-04-01 13:14 UTC, GrigorHar approved these changes

2024-04-02 11:22 UTC, yevgeniya-a requested changes
Plus several general remarks that also need to be fixed:
- Packages names has to start with a lowercase letter and mustn't contain spaces (Page Object => pageObject, Core => core, etc).
- Some of your files have names started with uppercase (Constant.ts, Reporter.ts, etc), some with lowercase (logger.ts, etc). Please use unified style or common logic. Utility/test files are commonly named with lowercase, files containing classes, page objects with uppercase.
- Config files names can be simplified - no need to use 'playwright' prefix in their names (playwright.config.ts => base.config.ts, playwright.local.config.ts => local.config.ts, etc).
- No API tests ot API interaction at all.
- 2 test suites instead of 3 (login + dashboard). Please add 1 more test suite, f.e. API one.

2024-04-02 11:22 UTC, yevgeniya-a commented on Core/Reporter.ts
> +class Reporter {
What is the purpose of this Reporter if it's not used anywhere. Either add its usage, or remove it

2024-04-02 11:22 UTC, yevgeniya-a commented on Core/logger.ts
> +module.exports = logger;
Are you sure that this is correct way of exporting here? Please integrate calling of this logger somewhere in your tests

2024-04-02 11:22 UTC, yevgeniya-a commented on Core/Constant.ts
> +    testUser = new User('arsenhovhannisyan', 'Portal2024+');
That data is more related to configuration rather than general constants or test data, also it usually tied with specific environment. So I'd suggest you to extract it somewhere in the configs. Also consider moving all the sensitive data to .env file or env variables

2024-04-02 11:22 UTC, yevgeniya-a commented on Core/Page Object/loginPage.ts
> +import {BasePage} from "./Base";
BasePage is imported but not used. Either extend LoginPage from this class or remove the import

2024-04-02 11:22 UTC, yevgeniya-a commented on Core/Page Object/dashbord.ts
> +        this.addDashboardButtonFromPopup = page.locator('button.bigButton__big-button--BmG4Q').getByText('Add');
Please reconsider your locator writing strategy. You're using specific ids in class names, though they're dynamic and change. You can use more flexible way. For example, to specify button that has class that starts with something you could use: button[class^="bigButton__big-button"]

2024-04-02 11:22 UTC, yevgeniya-a commented on Core/Page Object/dashbord.ts
> +        this.editDashboardButton = page.locator('button.ghostButton__ghost-button--r7c9T').getByText('Edit');
Also please consider to create not only pages but also components. For example, here you are reusing page.locator('button.ghostButton__ghost-button--r7c9T') element several times. It would be better to create separate class for that component with its own elements and call it here as a component class.

2024-04-02 11:22 UTC, yevgeniya-a commented on Core/Page Object/Base.ts
> +    this.sideBarMenu = page.locator('aside')
this.sideBarMenu is a component that has to be extracted into separate class and added only to pages which contain it

2024-04-02 11:22 UTC, yevgeniya-a commented on Core/Page Object/Base.ts
> +    this.loginPage = new LoginPage(this.page);
It is a bad idea to create these instances here. It's not in the logic of BasePage at all, also there is no guarantee that you'd need all the pages in your code, though you create all of them at once. Imagine that you'd have 100 pages, but will need only 1, how would you handle that? I'd suggest to create index.ts file, where you'd have method which would initialize and return needed page based on the argument that you pass for it, like const loginPage = getPage('login'). And getPage() method will create and return needed instance

2024-04-02 11:22 UTC, yevgeniya-a commented on tests/UI/dashboard.spec.ts
> +    await basePage.goto('https://reportportal.epam.com/');
Extract this url to config file as baseURL, it mustn't be hardcoded in tests

2024-04-02 11:22 UTC, yevgeniya-a commented on tests/UI/login.spec.ts
> +  await basePage.goto('https://reportportal.epam.com/');
Extract this url to config file as baseURL, it mustn't be hardcoded in tests

2024-04-02 11:22 UTC, yevgeniya-a commented on tests/UI/dashboard.spec.ts
> +    await basePage.dashboardPage.addNewDashboard.click()
Please consider to unify some actions into methods in the page object, f.e. addNewDashboard() and so on. This would add readability

2024-04-08 07:25 UTC, yevgeniya-a requested changes
Good job! The major remark is that you have only 1 test scenario instead of 3 requested by the task.

2024-04-08 07:25 UTC, yevgeniya-a commented on .env
> +USERNAME=arsenhovhannisyan
.env file should not be committed to the repo with real data.
You may leave keys empty. In that case, you will indicate which keys should be set, but will not share your real sensitive data.

2024-04-08 07:25 UTC, yevgeniya-a commented on config/playwright.config.ts
config names should be simplified by removing 'playwright' prefix

2024-04-08 07:25 UTC, yevgeniya-a commented on core/pageObject/dashbord.ts
> +        this.page = page;
You might add an abstract class which all your Page classes would extend. There you might put any common functionality, f.e. this.page = page; setting in constructor. Now you do it in every Page class separately, but if you make them extend some Common class, you might put it there

2024-04-08 07:25 UTC, yevgeniya-a commented on core/constant.ts
> +config();
config() call must be placed as early in your app as possible, that's why placing it in playwright.config file would be better. You even have a commented line there already - // require('dotenv').config();

2024-04-08 07:25 UTC, yevgeniya-a commented on core/pageObject/index.ts
> +export const getPage = (pageName: string, page: any) => {
You have a similar functionality in your BasePage now - getPage(). So this method here is redundant

2024-04-08 07:25 UTC, yevgeniya-a commented on tests/UI/dashboard.spec.ts
> +    await dashboardPage.fillDashboardPopupInputsAndSave('New Dashboard2', 'Some Description2')
You might also add the Dashboard class and pass the dashboard object instead of passing plain text to PO methods.

2024-04-08 07:25 UTC, yevgeniya-a commented on tests/UI/dashboard.spec.ts
Please add 2 more test scenarios together with dashboard.spec.ts

2024-04-10 14:02 UTC, yevgeniya-a requested changes

2024-04-10 14:02 UTC, yevgeniya-a commented on core/constant.ts
> +export class Dashboards {
I would recommend using dynamic data generation instead of hard-coding values for dashboard objects. Create a utility method in a separate utility file to generate a new dashboard on demand. Smth like:
// file: common.util.ts:
```
export function genDashboard() {
    const id = Date.now();
    return new Dashboard(`Dashboard-${id}`, `Description-${id}`);
}
```
And then, in tests, you'd call it as:
 ```
const dashboardData = genDashboard();
 const dashboardDataForEdit = genDashboard();
```

2024-04-10 14:02 UTC, yevgeniya-a commented on core/pageObject/Base.ts
> +   async goto(url: string) {
You specified the URL value in your configs as baseURL option, so here you don't need to specify the full URL again; only the part after the baseURL.
So this specific method could simply be:
```
async goto() {
  await this.page.goto('/');
}
```

2024-04-10 14:02 UTC, yevgeniya-a commented on core/pageObject/Base.ts
> +   getPage(pageName: string) {
I wanted to clarify my previous comment about the functionality and inheritance from BasePage, as I think it may have confused you. Since you have made BasePage the parent class, I suggest extracting the getPage() method from it and adding it to the index.ts file. This is because getPage() is like a factory method that creates instances of other classes, and should not belong to the classes it aims to create. 
If you prefer, you could choose to leave it here, but make it static as a second option.
So, f.e. it could be smth like:
```
static getPage(page: Page, pageName: string) {
       switch (pageName) {
           case 'login':
               return new LoginPage(page);
           case 'dashboard':
               return new Dashboards(page);
           default:
               throw new Error(`Page '${pageName}' not found.`);
       }
  }
```
And then in tests:
```
    dashboardPage = BasePage.getPage(page, 'dashboard');
    loginPage = BasePage.getPage(page, 'login');
    await loginPage.goto();
    await loginPage.loginAsTestUser();
```

2024-04-10 14:02 UTC, yevgeniya-a commented on tests/UI/dashboard.spec.ts
> +    await expect.soft(dashboardPage.dashboardNameFromMenu).toHaveText('New Dashboard1');
Validation must not be against hard-coded value 'New Dashboard1':
```
await expect.soft(dashboardPage.dashboardNameFromMenu).toHaveText(dashboardData.dashboardName);
```

2024-04-10 14:02 UTC, yevgeniya-a commented on tests/UI/dashboard.spec.ts
> +test.only('Check that user can delete newly add dashboard', async () => {
test.only must be replaced by test

2024-04-13 05:41 UTC, yevgeniya-a approved these changes

2024-04-15 09:36 UTC, merged